- name: Apacheインストール
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - httpd-devel

- name: 80番ポート開放
  lineinfile:
    dest: /etc/sysconfig/iptables
    state: present
    insertafter: "-A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT"
    line: "-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT"

- name: ファイアウォール再起動
  service: name=iptables state=restarted enabled=yes

- name: Apache起動
  service: name=httpd state=restarted enabled=yes
